server:
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_api_jwt
    password: root
    username: javaDbUser
  #    xayr h2
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:restdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
